name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  # geolocator: ^12.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  screenshot: ^3.0.0
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  location: ^7.0.0
  flutter_hooks: ^0.20.5
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.2
  path_provider: ^2.1.4

dev_dependencies:
  rename: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
